name: Test

on:
  push:

jobs:

  test:
    name: Test and Lint on Push
    runs-on: ubuntu-latest
    env:
      GO_VER: 1.15
      LINT_VER: v1.34
    steps:

    - name: Setup
      id: go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VER }}

    - name: Checkout
      id: setup
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Tidy
      run: |
        go mod tidy 
        go mod vendor

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: ${{ env.LINT_VER }}

    - name: Test
      run: go test -v -count=1 -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Cover
      uses: codecov/codecov-action@v1

      
    
